-- ============================================================================
-- The database as it exists BEFORE any of sql/migrations/ is applied.
--
-- This is what the backfill has to cope with, so it is deliberately shaped like
-- the real thing rather than like a tidy example. Applied after 00_shim.sql and
-- before the migrations. Test-only.
--
-- Two deliberate departures from the DDL in README.md:
--
--   1. NO `check (cohort in ('A','B'))`. The README declares it on five tables,
--      but production demonstrably holds cohort 'C' rows, so that constraint was
--      either never applied or has since been dropped. Reproducing it here would
--      make the fixture reject data the live database contains.
--
--   2. The README's open `"Allow read"` / `"Allow insert"` policies are omitted.
--      sql/secure_database.sql supersedes them with the `_auth_all` pattern but
--      never drops them by name, so live may hold either. RLS behaviour is
--      asserted against the migrations, not against this ambiguity.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Schema
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.students (
  student_id text PRIMARY KEY,
  cohort     text NOT NULL,
  name       text
);

CREATE TABLE IF NOT EXISTS public.present_students (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id text NOT NULL,          -- no FK: an orphan check-in is possible
  cohort     text NOT NULL,          -- denormalised copy taken at check-in
  timestamp  timestamptz NOT NULL DEFAULT now()
                                     -- no unique(student_id, date): the RPC guards it, the table does not
);

CREATE TABLE IF NOT EXISTS public.cancelled_sessions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date         date NOT NULL,
  cohort       text NOT NULL,
  is_cancelled boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (date, cohort)
);

CREATE TABLE IF NOT EXISTS public.class_schedule (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cohort      text NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  UNIQUE (cohort, day_of_week)
);

CREATE TABLE IF NOT EXISTS public.class_dates (
  id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date   date NOT NULL,
  cohort text NOT NULL,
  UNIQUE (date, cohort)
);

-- The singleton. One PIN, one window, one timer for the whole installation.
CREATE TABLE IF NOT EXISTS public.session_state (
  id                 integer PRIMARY KEY,
  pin                text,
  time_limit_seconds integer NOT NULL DEFAULT 300,
  session_start      timestamp,
  is_open            boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.flagged (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   text NOT NULL,
  session_date date NOT NULL,
  status       text NOT NULL DEFAULT 'flagged',
  created_at   timestamptz NOT NULL DEFAULT now()
                             -- no unique(student_id, session_date): flag_attendance is racy
);

CREATE TABLE IF NOT EXISTS public.flagged_resolutions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);  -- referenced by the RLS loop in secure_database.sql, used by no code

CREATE TABLE IF NOT EXISTS public.excused_absences (
  id         SERIAL PRIMARY KEY,
  student_id VARCHAR NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
  date       DATE NOT NULL,
  reason     VARCHAR,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (student_id, date)
);

CREATE TABLE IF NOT EXISTS public.report_settings (
  cohort          VARCHAR PRIMARY KEY,   -- re-keyed to cohort_id by the migrations
  instructor_name VARCHAR DEFAULT '',
  fi_name         VARCHAR DEFAULT '',
  updated_at      TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.canvas_row_mappings (
  canvas_key  VARCHAR PRIMARY KEY,
  student_id  VARCHAR REFERENCES public.students(student_id) ON DELETE CASCADE,
  ignored     BOOLEAN NOT NULL DEFAULT false,
  canvas_name VARCHAR,
  updated_at  TIMESTAMP DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- Data
--
-- Term runs Tue/Wed/Thu. The dates below are real weekdays in May 2026:
--   19 Tue, 20 Wed, 21 Thu, 26 Tue, 27 Wed, 28 Thu
--
-- Shaped to exercise every branch of the backfill:
--   * cohort C exists                    -> the letter README's CHECK rejects
--   * 27 May is cancelled for A only     -> per-cohort cancellation, which
--                                           buildWeeklyReport currently ignores
--   * on 27 May only B met               -> A must get no session that day
--   * on 28 May only A met               -> B and C must get no session that day
--   * S001 checked in twice on 19 May    -> the dedupe path (no unique constraint)
--   * S001 also checked in on 27 May     -> a check-in on a cancelled session
--   * S999 has a check-in but no student -> the reconciliation orphan bucket
--   * S002 is excused on 28 May          -> a day A met and S002 did not attend
--   * S004 disputes 26 May               -> a flag with no matching check-in
-- ----------------------------------------------------------------------------

INSERT INTO public.students (student_id, cohort, name) VALUES
  ('S001', 'A', 'Ama Boateng'),
  ('S002', 'A', 'Kwesi Owusu'),
  ('S003', 'B', 'Akua Darko'),
  ('S004', 'B', 'Yaw Asante'),
  ('S005', 'C', 'Efua Nyarko'),
  ('S006', 'C', NULL)                    -- no name: roster upload must fill, not overwrite
ON CONFLICT (student_id) DO NOTHING;

INSERT INTO public.present_students (student_id, cohort, timestamp) VALUES
  -- Tue 19 May: A, B and C all met
  ('S001', 'A', '2026-05-19T09:05:00Z'),
  ('S001', 'A', '2026-05-19T09:06:30Z'),  -- duplicate same day, must collapse to one
  ('S002', 'A', '2026-05-19T09:07:00Z'),
  ('S003', 'B', '2026-05-19T11:02:00Z'),
  ('S005', 'C', '2026-05-19T14:01:00Z'),
  ('S999', 'A', '2026-05-19T09:09:00Z'),  -- orphan: not in students
  -- Wed 20 May
  ('S001', 'A', '2026-05-20T09:03:00Z'),
  ('S003', 'B', '2026-05-20T11:01:00Z'),
  -- Thu 21 May
  ('S001', 'A', '2026-05-21T09:04:00Z'),
  ('S002', 'A', '2026-05-21T09:08:00Z'),
  ('S004', 'B', '2026-05-21T11:05:00Z'),
  -- Tue 26 May
  ('S002', 'A', '2026-05-26T09:02:00Z'),
  ('S003', 'B', '2026-05-26T11:04:00Z'),
  ('S005', 'C', '2026-05-26T14:03:00Z'),
  -- Wed 27 May: cancelled for A. S001 checked in anyway - the class was called
  -- off after some people had already marked, which is ordinary. Their record
  -- must survive: cancel_session() keeps present rows for exactly this reason.
  ('S001', 'A', '2026-05-27T09:02:00Z'),
  ('S003', 'B', '2026-05-27T11:00:00Z'),
  ('S004', 'B', '2026-05-27T11:06:00Z'),
  -- Thu 28 May: only A met
  ('S001', 'A', '2026-05-28T09:01:00Z');

INSERT INTO public.cancelled_sessions (date, cohort, is_cancelled) VALUES
  ('2026-05-27', 'A', true)
ON CONFLICT (date, cohort) DO NOTHING;

-- Tue/Wed/Thu for each cohort. Written by the app, then ignored by it: every
-- consumer is gated behind the hardcoded isValidClassDay first.
INSERT INTO public.class_schedule (cohort, day_of_week)
SELECT c, d FROM unnest(ARRAY['A','B','C']) c, unnest(ARRAY[2,3,4]) d
ON CONFLICT (cohort, day_of_week) DO NOTHING;

-- Deliberately empty: holds 0 rows in production. "Generate Class Dates" was
-- never run, which is why session detection falls back to "someone checked in".
-- Leaving this empty is what makes the backfill's reconstruction path the one
-- under test.

INSERT INTO public.session_state (id, pin, time_limit_seconds, session_start, is_open)
VALUES (1, '4821', 300, '2026-05-28T09:00:00', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.excused_absences (student_id, date, reason) VALUES
  ('S002', '2026-05-28', 'Medical appointment')
ON CONFLICT (student_id, date) DO NOTHING;

INSERT INTO public.flagged (student_id, session_date, status) VALUES
  ('S004', '2026-05-26', 'flagged'),     -- unresolved dispute
  ('S005', '2026-05-21', 'accepted');    -- accepted: must become a present record

INSERT INTO public.report_settings (cohort, instructor_name, fi_name) VALUES
  ('A', 'Dr. Mensah', 'Adjoa'),
  ('B', 'Dr. Mensah', 'Kojo'),
  ('C', 'Prof. Antwi', 'Adjoa')
ON CONFLICT (cohort) DO NOTHING;

INSERT INTO public.canvas_row_mappings (canvas_key, student_id, ignored, canvas_name) VALUES
  ('cid:101', 'S001', false, 'Boateng, Ama'),
  ('name:test student', NULL, true, 'Test Student')
ON CONFLICT (canvas_key) DO NOTHING;
